apiVersion: apps/v1
kind: Deployment
metadata:
  name: order-api
  namespace: resilience-lab
  labels:
    app: order-api
spec:
  replicas: 2
  selector:
    matchLabels:
      app: order-api
  template:
    metadata:
      labels:
        app: order-api
    spec:
      containers:
        - name: order-api
          image: order-api:local
          imagePullPolicy: Never
          ports:
            - containerPort: 8000
          env:
            - name: PAYMENT_SERVICE_URL
              value: "http://payment-api-svc.resilience-lab.svc.cluster.local:8000"
            - name: RESILIENT_MODE
              value: "true"
          securityContext:
            runAsNonRoot: true
            runAsUser: 10001
            runAsGroup: 10001
            allowPrivilegeEscalation: false
            capabilities:
              drop: ["ALL"]
          resources:
            requests:
              cpu: "100m"
              memory: "128Mi"
            limits:
              cpu: "250m"
              memory: "256Mi"
          readinessProbe:
            httpGet:
              path: /healthz
              port: 8000
            initialDelaySeconds: 3
            periodSeconds: 5
          livenessProbe:
            httpGet:
              path: /healthz
              port: 8000
            initialDelaySeconds: 5
            periodSeconds: 10
